version: "3.7"

services:
    client:
        container_name: client
        build: 
            context: ./client
            dockerfile: Dockerfile
        ports: 
            - '80:80'
            - '443:443'
        
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        command: gunicorn -k gevent mainApp.run:app --bind 0.0.0.0:8080
        container_name: server
        restart: always
        env_file:
            - /server/.env
            - /sever/.flaskenv
        environment: 
            - APP_NAME=StephenTracker
        expose:
            - 8080
